/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    Comments: typeof import('./src/components/ticket-listing/comments/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('./src/components/base/icon-field/index.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Indedx: typeof import('./src/components/ticket-listing/comments/indedx.vue')['default']
    InputField: typeof import('./src/components/base/input-field/index.vue')['default']
    InputIcon: typeof import('./src/components/base/input-icon/index.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListItem: typeof import('./src/components/base/list-item/index.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TicketInfo: typeof import('./src/components/ticket-listing/ticket-info/index.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
